--------------------------------------------------------
-- Archivo creado  - viernes-enero-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DB1"."EMPLEADO" 
   (	"ID_EMPLEADO" VARCHAR2(12 BYTE), 
	"NOMBRES" VARCHAR2(255 BYTE), 
	"APELLIDOS" VARCHAR2(255 BYTE), 
	"CURP" VARCHAR2(18 BYTE), 
	"PUESTO" VARCHAR2(255 BYTE), 
	"ID_JEFE" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DB1.EMPLEADO
SET DEFINE OFF;
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('YOL123456710','Yolanda','Perez','YOL1234567HDFXYD03','CEO',null);
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('GARD12345631','Daniel','Garcia','GARD123456HDFXYD03','Manager (Producción)','YOL123456710');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('LOPL12345661','Lucia','Lopez','LOPL123456HDFXYD03','Manager (Marketing)','YOL123456710');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('MARO12345613','Rocio','Martinez','MARO123456HDFXYD03','Manager (Operaciones)','GARD12345631');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('RAML12345657','Luis','Ramirez','RAML123456HDFXYD03','Manager (Diseño)','GARD12345631');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('HEPM12345681','Miguel','Hernandez','HEPM123456HDFXYD03','Manager (Ventas)','LOPL12345661');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('TORR12345644','Rosana','Torres','TORR123456HDFXYD03','Manager (Comunicación)','LOPL12345661');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('GOMC12345687','Claudia','Gomez','GOMC123456HDFXYD03','Empleado','MARO12345613');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('VEGH12345690','Hector','Vega','VEGH123456HDFXYD03','Empleado','MARO12345613');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('FERJ12345623','Jesus','Fernandez','FERJ123456HDFXYD03','Empleado','RAML12345657');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('DIAA12345673','Alexandra','Diaz','DIAA123456HDFXYD03','Empleado','HEPM12345681');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('MENJ12345681','Jose Ramon','Mendez','MENJ123456HDFXYD03','Empleado','TORR12345644');
Insert into DB1.EMPLEADO (ID_EMPLEADO,NOMBRES,APELLIDOS,CURP,PUESTO,ID_JEFE) values ('SANE12345669','Eva','Sanchez','SANE123456HDFXYD03','Empleado','TORR12345644');
--------------------------------------------------------
--  DDL for Index SYS_C008166
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB1"."SYS_C008166" ON "DB1"."EMPLEADO" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008167
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB1"."SYS_C008167" ON "DB1"."EMPLEADO" ("CURP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ID_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DB1"."TRG_ID_EMPLEADO" 
BEFORE INSERT ON Empleado
FOR EACH ROW
BEGIN
  :NEW.id_empleado := SUBSTR(:NEW.curp, 1, 10) || TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(10, 99)));
END;
/
ALTER TRIGGER "DB1"."TRG_ID_EMPLEADO" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DB1"."EMPLEADO" ADD UNIQUE ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB1"."EMPLEADO" ADD UNIQUE ("CURP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DB1"."EMPLEADO" ADD CONSTRAINT "FK_ID_JEFE" FOREIGN KEY ("ID_JEFE")
	  REFERENCES "DB1"."EMPLEADO" ("ID_EMPLEADO") ENABLE;
